### ISSUE TITLE
Dynamic rate limit support

### ISSUE THREAD

**Issue by Dragas** [cap5lut/cap5lut-ratelimits#2]
From a quick glance, it doesn't seem that current implementation of `ConcurrentRateLimit` supports dynamic rate limits. A dynamic rate limit is considered a rate limit that changes its capacity either between results or between particular moments in time. An example of that is discord bot API, which provides rolling rate limits.

**Comment by cap5lut** [comment]
Here is an example on how to do it: [complex rate limits](https://github.com/cap5lut/cap5lut-ratelimits#complex-rate-limits)
